// Auto-generated by scripts/generate-manifest.js
// Do not edit this file manually
window.MANIFEST_DATA = {
    "aurionpro-solutions-ltd": [
        "2026-Q2"
    ],
    "rr-kabel": [
        "2026-Q2"
    ]
};
